In [1]:
#Import NumPy
import numpy as np

#f(x) as a function
def f(x):
    return  10*x**2 - 2**10

#Python function for central difference mehtod for 1st order
def central_diff_first(f,x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

#Python function for central difference mehtod for 2nd order
def central_diff_second(f,x, h):
    return (f(x + h) - 2 * f(x) + f(x - h)) / (h**2)


In [2]:
#Function for Mean Absolute Error (MAE)
def MAE(expected_value, numerical_value):
    return np.mean(np.abs(expected_value - numerical_value))


In [3]:
#define some x values
x = np.arange(0,10,1)


In [4]:
#Calculating derivatives when h=0.1
h=0.1
y_prime_01 = central_diff_first(f,x,h)
y_prime2_01 = central_diff_second(f,x,h)

In [5]:
#Calculating derivatives when h=0.001
h=0.001
y_prime_0001 = central_diff_first(f,x,h)
y_prime2_0001 = central_diff_second(f,x,h)

In [6]:
#Analytical Solusions 
def f_prime(x):
    return 20 * x

def f_prime2(x):
    return 20 


In [7]:
y_prime = f_prime(x)
y_prime2 = f_prime2(x)

In [8]:
#MAE when h=0.1
mae_01 = MAE(y_prime,y_prime_01)
print(f"MAE = {mae_01}")

mae2_01 = MAE(y_prime2,y_prime2_01)
print(f"MAE = {mae2_01}")

MAE = 3.410605131648481e-13
MAE = 5.228173449722817e-12


In [9]:
#MAE when h=0.001
mae_0001 = MAE(y_prime,y_prime_0001)
print(f"MAE = {mae_0001}")

mae2_0001 = MAE(y_prime2,y_prime2_0001)
print(f"MAE = {mae2_0001}")

MAE = 4.524736141320318e-11
MAE = 7.70414771977812e-08


import matplotlib.pyplot as plt
plt.plot(x,y_prime)
plt.plot(x,y_prime_01)
plt.plot(x,y_prime_0001)

In [10]:
y_prime

array([  0,  20,  40,  60,  80, 100, 120, 140, 160, 180])

In [11]:
y_prime_01

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [12]:
h=0.1
central_diff_first(f,x,0.1)

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [13]:
h=0.001
central_diff_first(f,x,0.001)

array([  0.,  20.,  40.,  60.,  80., 100., 120., 140., 160., 180.])

In [14]:
f(x)

array([-1024, -1014,  -984,  -934,  -864,  -774,  -664,  -534,  -384,
        -214], dtype=int32)

In [15]:
def f(x):
    return x**3 + 10 * x**2 - 2**10

def central_difference_first_derivative(x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

def central_difference_second_derivative(x, h):
    return (f(x + h) - 2 * f(x) + f(x - h)) / (h**2)

# Specify the value of x and the step size h
x = 1.5
h = 0.1

# Compute the first derivative
f_prime = central_difference_first_derivative(x, h)
print("First derivative:", f_prime)

# Compute the second derivative
f_double_prime = central_difference_second_derivative(x, h)
print("Second derivative:", f_double_prime)


First derivative: 36.75999999999988
Second derivative: 29.000000000007724


In [16]:
def f(x):
    return 10 * x**2 - 2**10

def central_difference_first_derivative(x, h):
    return (f(x + h) - f(x - h)) / (2 * h)

def central_difference_second_derivative(x, h):
    return (f(x + h) - 2 * f(x) + f(x - h)) / (h**2)

def absolute_error(expected_value, numerical_value):
    return abs(expected_value - numerical_value)

# Specify the value of x and the step sizes h
x = 1.5
h1 = 0.1
h2 = 0.001

# Compute the expected values analytically
f_prime_expected = 20 * x
f_double_prime_expected = 20

# Compute the numerical approximations using central difference method
f_prime_numerical_h1 = central_difference_first_derivative(x, h1)
f_prime_numerical_h2 = central_difference_first_derivative(x, h2)
f_double_prime_numerical_h1 = central_difference_second_derivative(x, h1)
f_double_prime_numerical_h2 = central_difference_second_derivative(x, h2)

# Compute the mean absolute errors
error_f_prime_h1 = absolute_error(f_prime_expected, f_prime_numerical_h1)
error_f_prime_h2 = absolute_error(f_prime_expected, f_prime_numerical_h2)
error_f_double_prime_h1 = absolute_error(f_double_prime_expected, f_double_prime_numerical_h1)
error_f_double_prime_h2 = absolute_error(f_double_prime_expected, f_double_prime_numerical_h2)

# Print the mean absolute errors
print("Mean Absolute Error for f' (h=0.1):", error_f_prime_h1)
print("Mean Absolute Error for f' (h=0.001):", error_f_prime_h2)
print("Mean Absolute Error for f'' (h=0.1):", error_f_double_prime_h1)
print("Mean Absolute Error for f'' (h=0.001):", error_f_double_prime_h2)


Mean Absolute Error for f' (h=0.1): 0.0
Mean Absolute Error for f' (h=0.001): 2.7284841053187847e-11
Mean Absolute Error for f'' (h=0.1): 4.543920795185841e-12
Mean Absolute Error for f'' (h=0.001): 5.0495145842432976e-08


In [17]:
def absolute_error(expected_value, numerical_value):
    return abs(expected_value - numerical_value)

# Specify the value of x and the step sizes h
x = 1.5
h1 = 0.1
h2 = 0.001

# Compute the numerical approximations using central difference method
f_prime_numerical_h1 = central_difference_first_derivative(x, h1)
f_prime_numerical_h2 = central_difference_first_derivative(x, h2)
f_double_prime_numerical_h1 = central_difference_second_derivative(x, h1)
f_double_prime_numerical_h2 = central_difference_second_derivative(x, h2)

# Compute the expected values using analytical solutions
f_prime_expected = 20 * x
f_double_prime_expected = 20

# Compute the mean absolute errors
error_f_prime_h1 = absolute_error(f_prime_expected, f_prime_numerical_h1)
error_f_prime_h2 = absolute_error(f_prime_expected, f_prime_numerical_h2)
error_f_double_prime_h1 = absolute_error(f_double_prime_expected, f_double_prime_numerical_h1)
error_f_double_prime_h2 = absolute_error(f_double_prime_expected, f_double_prime_numerical_h2)

# Print the mean absolute errors
print("Mean Absolute Error for f' (h=0.1):", error_f_prime_h1)
print("Mean Absolute Error for f' (h=0.001):", error_f_prime_h2)
print("Mean Absolute Error for f'' (h=0.1):", error_f_double_prime_h1)
print("Mean Absolute Error for f'' (h=0.001):", error_f_double_prime_h2)


Mean Absolute Error for f' (h=0.1): 0.0
Mean Absolute Error for f' (h=0.001): 2.7284841053187847e-11
Mean Absolute Error for f'' (h=0.1): 4.543920795185841e-12
Mean Absolute Error for f'' (h=0.001): 5.0495145842432976e-08


In [8]:
def trapezoidal_rule(f, a, b, n):
    h = (b - a) / n
    integral = 0.5 * (f(a) + f(b))
    for i in range(1, n):
        x = a + i * h
        integral += f(x)
    integral *= h
    return integral

def simpsons_rule(f, a, b, n):
    if n % 2 != 0:
        raise ValueError("Number of subintervals must be even.")
    h = (b - a) / n
    integral = f(a) + f(b)
    for i in range(1, n):
        x = a + i * h
        coeff = 2 if i % 2 == 0 else 4
        integral += coeff * f(x)
    integral *= h / 3
    return integral



In [9]:
# Functions based on the graph
def f1(x):
    return 2.5 * x

def f2(x):
    return -2.5 * x + 20

a = 0  # Lower limit for straight line 1
b = 4  # Upper limit for straight line 1
n = 100  # Number of subintervals

result1 = trapezoidal_rule(f1, a, b, n)

a = 4  # Lower limit for straight line 2
b = 8  # Upper limit for straight line 2
result2 = trapezoidal_rule(f2, a, b, n)

total_area = result1 + result2
print("The total area using Trapezoidal rule:", total_area)


The total area using Trapezoidal rule: 40.0


In [11]:
# Functions based on the graph
def f1(x):
    return 2.5 * x

def f2(x):
    return -2.5 * x + 20

a = 0  # Lower limit for straight line 1
b = 4  # Upper limit for straight line 1
n = 100  # Number of subintervals

result1 = simpsons_rule(f1, a, b, n)

a = 4  # Lower limit for straight line 2
b = 8  # Upper limit for straight line 2
result2 = simpsons_rule(f2, a, b, n)

total_area = result1 + result2
print("The total area using Simpson's rule:", total_area)


The total area using Simpson's rule: 40.0
